name: Windows Self-Hosted Runner - Hello

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug - show workspace and files
        shell: powershell
        run: |
          Write-Host "Current directory:"
          Get-Location
          Write-Host "Repo contents:"
          dir
          Write-Host "Scripts folder contents:"
          dir .\scripts

      - name: Run PowerShell script
        shell: powershell
        run: |
         powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\hello.ps1
